### ISSUE TITLE
'Check Transaction' indicates it supports transaction private key, but does not

### ISSUE THREAD

**Issue by zpalmtree** [TurtlePay/blockchain-explorer#3]
We can see here it only attempts to use the input as a private view key: https://github.com/TurtlePay/blockchain-explorer/blob/master/js/transaction.js#L129

**Comment by brandonlehmann** [comment]
The more relevant code is probably here -> https://github.com/TurtlePay/blockchain-explorer/blob/23cdf819539f278bfd0308fbf8b21708ef908a95/js/transaction.js#L171

**Comment by brandonlehmann** [comment]
Resolved in https://github.com/TurtlePay/blockchain-explorer/commit/56b36d7bf6e44c22a0f3d502d2559c9c79b351b1
